version: '3.8'

services:
  mongodb1:
    image: mongo:4.4
    container_name: mongodb_container1
    restart: always
    ports:
      - 27800:27017
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: jahir
      MONGO_INITDB_ROOT_PASSWORD: jahir3323
  mongodb2:
    image: mongo:4.4
    container_name: mongodb_container2
    restart: always
    ports:
      - 27900:27017
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: jahir
      MONGO_INITDB_ROOT_PASSWORD: jahir3323
    volumes:
      - ./mongodb_data:/data/db

networks:
  backend:
    external:
      name: proxy

