version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1433:1433
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./:/etc/nginx/certs

networks:
  default:
    external:
      name: proxy
