version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1433:1433
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - /home/jahir/bd/proxy/Jahir:/etc/nginx/certs
  mongodb:
    image: mongo:4.4
    container_name: mongodb_container
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: jahir
      MONGO_INITDB_ROOT_PASSWORD: Jahir_3323
    volumes:
      - ./mongodb_data:/data/db

networks:
  backend:
  default:
    external:
      name: proxy

